export type ApprovalEnvironment = 'DEVELOPMENT' | 'PRODUCTION';

export type ApprovalModule = 'IDENTITY' | 'LIVELINESS' | 'INCOME' | 'RECOVA' | 'CREDIT';

export interface ApprovalUserData {
  /** First name of the user */
  firstName?: string;
  /** Last name of the user */
  lastName?: string;
  /** 11-digit Bank Verification Number (BVN) */
  bvn?: string;
  /** 11-digit National Identity Number (NIN) */
  nin?: string;
  /** Email address of the user */
  email?: string;
  /** Date of birth in ISO 8601 format (e.g. "2000-10-01") */
  dob?: string;
  /** Alias for dob */
  dateOfBirth?: string;
  /** Phone number with country code (e.g. "+2348012345678") */
  phone?: string;
}

export interface ApprovalConfig {
  /** Your CreditChek public API key */
  publicKey: string;
  /** Unique session UUID generated by your backend via /v1/auth/widget-session/create */
  sessionId: string;
  /** Target environment (defaults to 'DEVELOPMENT') */
  environment?: ApprovalEnvironment;
  /** Verification modules (defaults to ['IDENTITY']) */
  modules?: ApprovalModule[];
  /** Optional prefill user data */
  userData?: ApprovalUserData;
}

export interface SessionResultSuccess {
  status: 'success';
  sessionId: string;
  message: string;
}

export interface SessionResultCancelled {
  status: 'cancelled';
}

export interface SessionResultError {
  status: 'error';
  code: string;
  message: string;
}

export type SessionResult =
  | SessionResultSuccess
  | SessionResultCancelled
  | SessionResultError;
